id: P004217
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12668
  title: གཟུགས་ཀྱི་ཉི་མའི་རྣམ་ཐར། ༼ཀ་སྦུག་པར་མ།༽
  author: ''
  volumes:
    4516d455192b416d95e007a07b2168c6:
      image_group_id: I1KG12695
      title: ''
      volume_number: 1
      total_pages: 282
