id: P004217
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:01:58.774726
source_metadata:
  id: bdr:W1KG12668
  title: གཟུགས་ཀྱི་ཉི་མའི་རྣམ་ཐར། ༼ཀ་སྦུག་པར་མ།༽
  author: ''
  volumes:
    4516d455192b416d95e007a07b2168c6:
      image_group_id: I1KG12695
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
